name: Azure Bicep VM Linux Deployment
on: 
  workflow_dispatch:
    inputs:
      vm_vnet:
      description: 'Vnet for VM'
      type: choice
      required: true
      options:
        - name: "sub-shared-corp-prod-01"
          vnet_name: "AZSFTPEUS201-vnet"
          vnet_resourcegroup: "sandbox-aad-rg"
        - name: "sub-shared-corp-prod-01"
          vnet_name: "Spk-Shared-Corp-Prod-CUS-VNET"
          vnet_resourcegroup: "sandbox-prod-rg"
        - name: "sub-shared-corp-prod-01"
          vnet_name: "Spk-Shared-Corp-Prod-EUS2-VNET"
          vnet_resourcegroup: "prod-rg"
        - name: "sub-shared-corp-sandbox-01"
          vnet_name: "CIRI-TEST-NETWORK"
          vnet_resourcegroup: "sandbox-test-rg"
        - name: "sub-shared-corp-sandbox-01"
          vnet_name: "sanbox-infra-vnet"
          vnet_resourcegroup: "sandbox-infra-rg"
        - name: "sub-shared-corp-sandbox-01"
          vnet_name: "Spk-Patch-MGMT"
          vnet_resourcegroup: "patch-mgmt-rg"
        - name: "sub-shared-corp-sandbox-01"
          vnet_name: "VNET-SANDBOX-CORE-EUS2"
          vnet_resourcegroup: "core-sandbox-rg"
        - name: "sub-ulri-corp-prod-01"
          vnet_name: "Spk-ULRI-Corp-Prod-CUS-VNET"
          vnet_resourcegroup: "ulri-prod-rg"
        - name: "sub-ulri-corp-prod-01"
          vnet_name: "Spk-ULRI-Corp-Prod-EAST-VNET"
          vnet_resourcegroup: "east-prod-rg"
        - name: "sub-ulri-corp-prod-01"
          vnet_name: "Spk-ULRI-Corp-Prod-EUS2-VNET"
          vnet_resourcegroup: "eus2-prod-rg"
